-

diff --git a/.github/workflows/fabbot.yml b/.github/workflows/fabbot.yml
--- a/.github/workflows/fabbot.yml
+++ b/.github/workflows/fabbot.yml
@@ -92,3 +92,46 @@ jobs:
             } || {
               echo "::notice::No merge commits found. Good job! 🎉"
             }
+
+      - name: Check test-case methods
+        if: always()
+        run: |
+          rm -rf b && cp -a a b && cd b
+          find -wholename '**/Tests/**.php' \
+            | while read -r FILE; do
+              sed -i -E 's/^(    public function test.*): void$/\1/' "$FILE"
+            done
+          cd ..
+
+          if diff -q -r --no-dereference a/ b/ >/dev/null; then
+            echo "::notice::Test case methods are correctly formatted. Good job! 🎉"
+          else
+            echo "::error::Test case methods should not have a return type. Please apply the patch below."
+            echo -e "\n \ngit apply - <<'EOF_PATCH'"
+            diff -u -p -r --no-dereference --color=always a/ b/ || true
+            echo -e "EOF_PATCH\n \n"
+            echo "Then commit the changes and push to your PR branch."
+            exit 1
+          fi
+
+
+      - name: Check @deprecated annotations
+        if: always()
+        run: |
+          rm -rf b && cp -a a b && cd b
+          find -name '*.php' \
+            | while read -r FILE; do
+              sed -i -E 's/(@deprecated since )([0-9])/\1Symfony \2/' "$FILE"
+            done
+          cd ..
+
+          if diff -q -r --no-dereference a/ b/ >/dev/null; then
+            echo "::notice::@deprecated annotations are correctly formatted. Good job! 🎉"
+          else
+            echo "::error::@deprecated annotations should mention Symfony. Please apply the patch below."
+            echo -e "\n \ngit apply - <<'EOF_PATCH'"
+            diff -u -p -r --no-dereference --color=always a/ b/ || true
+            echo -e "EOF_PATCH\n \n"
+            echo "Then commit the changes and push to your PR branch."
+            exit 1
+          fi
