-

diff --git a/.github/workflows/fabbot.yml b/.github/workflows/fabbot.yml
--- a/.github/workflows/fabbot.yml
+++ b/.github/workflows/fabbot.yml
@@ -153,6 +153,7 @@ jobs:
               catch (Exception $e) { echo "Error in $argv[1]: {$e->getMessage()}\n"; exit(1); }
             ' "$FILE"
             done
+          cd ..
 
       - name: Check JSON files
         if: always()
@@ -166,3 +167,57 @@ jobs:
               catch (Exception $e) { echo "Error in $argv[1]: {$e->getMessage()}\n"; exit(1); }
               ' "$FILE"
             done
+          cd ..
+
+      - name: Check exception messages
+        if: always()
+        run: |
+          rm -rf b && cp -a a b && cd b
+          find -name '*.php' \
+            | while read -r FILE; do php -r "$(cat <<'EOF'
+              $new = preg_replace_callback('{throw new ([^\(]+)\((.+?)\);}', function ($match) {
+                $contents = $match[2];
+
+                // %s::%s() -> "%s::%s()"
+                $contents = preg_replace('{(?<= )%s\:\:%s(\(\))?}', '"%s::%s()"', $contents);
+                $contents = preg_replace('{\(\'%s\:\:%s(\(\))?}', '(\'"%s::%s()"', $contents);
+
+                // %s() -> "%s()"
+                $contents = preg_replace('{(?<= )%s(\(\))}', '"%s$1"', $contents);
+                $contents = preg_replace('{\(\'%s(\(\))}', '(\'"%s$1"', $contents);
+
+                // %s -> "%s" after a space
+                $contents = preg_replace('{(?<= )%s}', '"%s"', $contents);
+                $contents = preg_replace('{\(\'%s}', '(\'"%s"', $contents);
+
+                return sprintf('throw new %s(%s);', $match[1], $contents);
+              }, $old = file_get_contents($argv[1]));
+
+              // ensure there is a dot at the end of the exception message
+              // except for files under Tests/
+              if (false === strpos($argv[1], '/Tests/')) {
+                $new = preg_replace_callback('{throw new ([^\(]+)\((sprintf\()?(\'|")(.+?)(?<!\\\)(\3)}', function ($match) {
+                  if ('UnexpectedTypeException' === $match[1]) {
+                    return $match[0];
+                  }
+
+                  return sprintf('throw new %s(%s%s%s%s%s', $match[1], $match[2], $match[3], $match[4], \in_array($match[4][\strlen($match[4]) - 1], ['.', '!', '?', ' ']) ? '' : '.', $match[5]);
+                }, $new);
+              }
+
+              if ($new !== $old) {
+                file_put_contents($argv[1], $new);
+              }
+          EOF
+            )" "$FILE"
+            done
+          cd ..
+
+          if ! diff -q -r --no-dereference a/ b/ >/dev/null; then
+            echo "::error::Some exception messages might need a tweak. Please consider the patch below."
+            echo -e "\n \n git apply - <<'EOF_PATCH'"
+            diff -u -p -r --no-dereference --color=always a/ b/ || true
+            echo -e "EOF_PATCH\n \n"
+            echo "Then commit the changes and push to your PR branch."
+            exit 1
+          fi
