-

diff --git a/.github/workflows/fabbot.yml b/.github/workflows/fabbot.yml
--- a/.github/workflows/fabbot.yml
+++ b/.github/workflows/fabbot.yml
@@ -21,6 +21,7 @@ jobs:
           REPO_OWNER="${{ github.repository_owner }}"
           REPO_NAME="${{ github.event.repository.name }}"
 
+          pip install codespell &
           composer global require -q friendsofphp/php-cs-fixer &
 
           mkdir a
@@ -64,8 +65,6 @@ jobs:
       - name: Check for common typos
         if: always()
         run: |
-          pip install codespell
-
           rm -rf b && cp -a a b && cd b
           codespell -L invokable --check-filenames -w || true
           cd ..
@@ -133,5 +132,21 @@ jobs:
             diff -u -p -r --no-dereference --color=always a/ b/ || true
             echo -e "EOF_PATCH\n \n"
             echo "Then commit the changes and push to your PR branch."
+            exit 1
+          fi
+
+      - name: Check PR header
+        if: always()
+        run: |
+          PR_TITLE="${{ github.event.pull_request.title }}"
+          PR_BODY="${{ github.event.pull_request.body }}"
+
+          if [[ ! "$PR_BODY" =~ \|\ License[\ ]+\|\ MIT ]]; then
+            echo "::error::You must add the standard Symfony PR contribution header in the description (see https://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request)."
+            exit 1
+          fi
+
+          if [[ "$PR_TITLE" =~ (feat|fix|docs|style|refactor|perf|test|chore|revert|build|ci|types?|wip): ]]; then
+            echo "::error::Don't use conventional prefixes in PR title. We'll add one while merging."
             exit 1
           fi
