-

diff --git a/.github/workflows/fabbot.yml b/.github/workflows/fabbot.yml
--- a/.github/workflows/fabbot.yml
+++ b/.github/workflows/fabbot.yml
@@ -44,6 +44,7 @@ jobs:
           wait
 
       - name: Check code style
+        if: always()
         run: |
           cp -a a b && cd b
           ~/.composer/vendor/bin/php-cs-fixer fix --using-cache no --show-progress none
@@ -53,6 +54,26 @@ jobs:
             echo "::notice::PHP-CS-Fixer found no style issues. Code is clean! 🎉"
           else
             echo "::error::PHP-CS-Fixer found style issues. Please apply the patch below."
+            echo -e "\n \ngit apply - <<'EOF_PATCH'"
+            diff -u -p -r --no-dereference --color=always a/ b/ || true
+            echo -e "EOF_PATCH\n \n"
+            echo "Then commit the changes and push to your PR branch."
+            exit 1
+          fi
+
+      - name: Check for common typos
+        if: always()
+        run: |
+          pip install codespell
+
+          rm -rf b && cp -a a b && cd b
+          codespell -L invokable --check-filenames -w || true
+          cd ..
+
+          if diff -q -r --no-dereference a/ b/ >/dev/null; then
+            echo "::notice::codespell found no typos issues. Code is clean! 🎉"
+          else
+            echo "::error::PHP-CS-Fixer found typos. Please apply the patch below."
             echo -e "\n \ngit apply - <<'EOF_PATCH'"
             diff -u -p -r --no-dereference --color=always a/ b/ || true
             echo -e "EOF_PATCH\n \n"
